__Tarea 20: Ejercicio 1 (Jueves 9 de Noviembre):__ Crear una rutina que construya $A$ y $\vec b$ para este sistema. Resuelvalo utilizando la función `inv` y grafique $\vec f$ utilizando la funcion `pcolormesh`. Recuerde que aqui $\vec f$ es un vector, para volverlo de nuevo una matriz con entradas $f_{i,j}$ pueden usar la función `reshape`.

In [9]:
f=zeros(225) #creamos una rutina que forma los elementos de la diagonal y de las demas diagonales, para ello creamos una lista de 
#225 ceros
i=1
while i<226
f[i]=-4
i=i+16
end
j=2
while j<211
f[j]=1
j=j+16
end
k=16
while  k<225
f[k]=1
k=k+16
end
l=6
while l<151
f[l]=1
l=l+16
end
m=76
while m<221
f[m]=1
m=m+16
end
f[66]=0#finalmete colocamos los ceros en los lugares adecuados de la diagonal
f[80]=0
f[146]=0
f[160]=0
A = reshape(f,(15,15))

15×15 Array{Float64,2}:
 -4.0   1.0   0.0   0.0   0.0   1.0  …   0.0   0.0   0.0   0.0   0.0   0.0
  1.0  -4.0   1.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   1.0  -4.0   1.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   1.0  -4.0   1.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   1.0  -4.0   0.0      1.0   0.0   0.0   0.0   0.0   0.0
  1.0   0.0   0.0   0.0   0.0  -4.0  …   0.0   1.0   0.0   0.0   0.0   0.0
  0.0   1.0   0.0   0.0   0.0   1.0      0.0   0.0   1.0   0.0   0.0   0.0
  0.0   0.0   1.0   0.0   0.0   0.0      0.0   0.0   0.0   1.0   0.0   0.0
  0.0   0.0   0.0   1.0   0.0   0.0      1.0   0.0   0.0   0.0   1.0   0.0
  0.0   0.0   0.0   0.0   1.0   0.0     -4.0   0.0   0.0   0.0   0.0   1.0
  0.0   0.0   0.0   0.0   0.0   1.0  …   0.0  -4.0   1.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   1.0  -4.0   1.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   1.0  -4.0   1.0   0.0
 

In [10]:
b=[]#luego creamos el vector b
for i in 1:15
    push!(b,0)
end
b[5]=70.7101
b[10]=100
b[15]=70.7101

70.7101

In [11]:
b'

1×15 Array{Any,2}:
 0  0  0  0  70.7101  0  0  0  0  100  0  0  0  0  70.7101

In [13]:
g=-inv(A)*b#se recuelve el sistema

15-element Array{Any,1}:
  1.30458
  3.37337
  7.41824
 15.8086 
 33.4594 
  1.84496
  4.77067
 10.491  
 22.3568 
 47.3189 
  1.30458
  3.37337
  7.41824
 15.8086 
 33.4594 

In [30]:
r=reshape(g,(5,3))

5×3 Array{Any,2}:
  1.30458   1.84496   1.30458
  3.37337   4.77067   3.37337
  7.41824  10.491     7.41824
 15.8086   22.3568   15.8086 
 33.4594   47.3189   33.4594 

In [31]:
using PyPlot

In [32]:
pcolormesh(r)#se grafica la solución de la ec de laplace

PyObject <matplotlib.collections.QuadMesh object at 0x7fcb7b944c50>